title: Syed Arefinul Haque, PhD Student - Network Science
description: > # this means to ignore newlines until "baseurl:"
  Network Scientist and Researcher @ Network Science Institute, Northeastern University
# permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Syed Arefinul Haque # add your name
author-img: avatar.jpg # add your photo
about-author:  PhD Student in the Network Science Institute @ Northeastern Univeristy (Boston, MA, USA).  I study gender bias and science of science using network science methods. # add description
social-twitter: syedarehaq # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: syedarehaq # add your Github handle
social-linkedin: syedarehaq # add your Linkedin handle
social-scholar: https://scholar.google.com/citations?user=u3o8UR4AAAAJ&hl=en
social-cv:
# social-email: # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
#analytics: # Google Analytics

# Build Settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
 # - jekyll-readme-index

paginate: 8
paginate_path: "/page/:num"

# readme_index:
#   enabled:          false
#   remove_originals: false
#   with_frontmatter: false

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
